# Generated by Django 4.1 on 2025-05-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('ESTÚDIO', 'estudio'), ('AUTOMAÇÃO', 'automacao'), ('CÓDIGO', 'codigo'), ('STORYTELLING', 'storytelling')], default='', max_length=100),
        ),
    ]
