# Generated by Django 4.1 on 2025-05-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='link',
            field=models.TextField(blank='False'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='tutorial',
            field=models.TextField(blank='False'),
        ),
    ]
